repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: 'README\.md'
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
      - id: ruff-format
#   - repo: local
#     hooks:
#       - id: increment-build-number
#         name: Increment Build Number
#         language: system
#         entry: python .pre-commit-scripts/increment_version.py
#         pass_filenames: false
